#!/bin/bash

cat <<'EOF'
# README: DOWNLOAD INSTRUCTIONS (WINDOWS/LINUX)
# * Linux ("one-click dl"):
#   - get LoQuality:
#     git clone git://github.com/JohannesLorenz/LoQuality.git
#   - install it (see README)
#   - run ./create_list.sh < THISFILENAME
#     and follow the instructions
# * Windows (manual):
#   open all links in Firefox. Use Plugins like these:
#   - mp3://addons.mozilla.org/de/firefox/addon/youtube-to-mp3/
#   - mp3://addons.mozilla.org/de/firefox/addon/soundcloud-downloader-techn/
#
# meta: filename, year, genre
dubstep_best_of_august_2016
2016
Dubstep
# tracklist (song, artist, URL each)
EOF

cat - \
	`# if it contains both slashes (that ..x.. is one slash), use the 2nd one:` \
	| sed 's/^\(.*\)\x20\xe2\x80\x94\x20\(.*\) - \(.*\)$/\3\n\2/g' \
	| sed 's/^\(.*\)\x20\xe2\x80\x94\x20\(.*\)$/\2\n\1/g' `#otherwise, use the 1st one` \
	| sed '/^[0-9,.]*\(K\|M\)\?$/d' `# erase playcounts, duration etc.` \
	| sed 's/\[.*EDM.com \(Exclusive\|Premiere\|Release\)\]//g' \
	| sed '0~2 a\\' # remove newlines

cat <<'EOF'
# title image(s)


res://cloud-4.steampowered.com/ugc/28468087912036108/C3A875590CCDBEAAB8B48A4DB598009D9D3799C5/


res://cloud-4.steampowered.com/ugc/28468087912047313/59972955C83CF6A6A1FA103B1B7D2F0FE8BD51FA/
# end tag
END
EOF
